name: Bug report
description: Report something broken or confusing.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug. If you can include a minimal config + prompt suite, it makes debugging much faster.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Include error messages and what you expected instead.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. export FT_AUDIT_CONFIG=...
        2. ft-audit-mcp serve --profile full
        3. ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version / commit
      placeholder: "`git rev-parse HEAD`"
  - type: textarea
    id: logs
    attributes:
      label: Logs / traceback
      render: shell

